spring.application.name=leavepilot


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.servlet.context-path=/leavepilot
server.port=${PORT:8080}

app.jwt.secret=ghvbdaf7toq8wyeigah2ot8yrewhg578yiLFH97GYI
app.jwt.expiration-ms=10000000
app.cors.origin=app.cors.origin=http://localhost:5173,http://leavepilot-frontend-anant.s3-website-us-east-1.amazonaws.com