spring.application.name=leavepilot

spring.datasource.url=jdbc:mysql://localhost:3306/leavepilot_db
spring.datasource.username=root
spring.datasource.password=Mathura@12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.servlet.context-path=/leavepilot
server.port=${PORT:8080}

app.jwt.secret=ghvbdaf7toq8wyeigah2ot8yrewhg578yiLFH97GYI
app.jwt.expiration-ms=10000000
app.cors.origin=https://ambitious-coast-069979500-preview.eastasia.2.azurestaticapps.net