spring.application.name=leavepilot


spring.datasource.url=jdbc:mysql://leavepilot-mysql.cc9icg04i4uw.us-east-1.rds.amazonaws.com:3306/leavepilot_db?createDatabaseIfNotExist=true
spring.datasource.username=leavepilotadmin
spring.datasource.password=Leave321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.servlet.context-path=/leavepilot
server.port=${PORT:8080}

app.jwt.secret=ghvbdaf7toq8wyeigah2ot8yrewhg578yiLFH97GYI
app.jwt.expiration-ms=10000000
app.cors.origin=http://localhost:5173,https://ambitious-coast-069979500.2.azurestaticapps.net
